version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/finance_client.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf-8
    level: WARNING
    formatter: simple

loggers:
  finance_client:
    level: INFO
    handlers: [file, console]
    propagate: no