from enum import Enum
from typing import NamedTuple

buy = "buy"
sell = "sell"
margin_buy = "margin_buy"
margin_sell = "margin_sell"

ORDER_BUY_CLASS = "StockBuyBtn"
ORDER_SELL_CLASS = "StockSellBtn"

order_types = [buy, sell, margin_buy, margin_sell]

symbol_page_to_order_element = {
    buy: "現物買",
    sell: "現物売",
    margin_buy: "信用買",
    margin_sell: "信用売",
}

JP_TSE_Prime = "JP_TSE_Prime"
JP_TSE_Standard = "JP_TSE_Standard"
JP_TSE_Growth = "JP_TSE_Growth"
JP_TSE_ETF = "JP_TSE_ETF"
JP_TSE_REIT = "JP_TSE_REIT"
JP_Regional_Markets = "JP_Regional_Markets"
JP_Others = "JP_Others"

MARKET_OPTION_JP = {
    JP_TSE_Prime: "東証P",
    JP_TSE_Standard: "東証S",
    JP_TSE_Growth: "東証G",
    JP_TSE_ETF: "東証ETF",
    JP_TSE_REIT: "東証REIT",
    JP_Regional_Markets: "地方市場",
    JP_Others: "その他"
}

ERROR_BUDGET_IS_SHORT = "WECEK00210"

AVAILABLE_SECTOR_OPTIONS = {
    0: "水産・農林業",
    1: "鉱業",
    2: "建設業",
    3: "食料品",
    4: "繊維製品",
    5: "パルプ・紙",
    6: "化学",
    7: "医薬品",
    8: "石油・石炭製品",
    9: "ゴム製品",
    10: "ガラス・土石製品",
    11: "鉄鋼",
    12: "非鉄金属",
    13: "金属製品",
    14: "機械",
    15: "電気機器",
    16: "輸送用機器",
    17: "精密機器",
    18: "その他製品",
    19: "電気・ガス業",
    20: "陸運業",
    21: "海運業",
    22: "空運業",
    23: "倉庫・運輸関連業",
    24: "通信業",
    25: "卸売業",
    26: "小売業",
    27: "銀行業",
    28: "証券業",
    29: "保険業",
    30: "その他の金融業",
    31: "不動産業",
    32: "サービス業",
    33: "その他"
}


class COMMON_HEADER(Enum):
    HOME = 0
    MARKET = 1
    JP_STOCK = 2
    STOCK = 3
    TRUST = 4
    CLAIM = 5
    FX = 6
    OPTION = 7
    CFD = 8
    GOLD = 9
    NISA = 10
    IDECO = 11
    OTHER = 12

class TRADE_HEADER(Enum):
    TRADE_EXCHANGE = 0  # 新規注文取引所
    TRADE_PTS = 1  # 新規注文PTS
    ACCUMULATION = 2  # 積立
    CREDIT_SETTLEMENT = 3  # 信用返済・取引現渡
    OWNED_STOCKS = 4  # 保有株式
    ORDER_INQUIRY = 5  # 注文照会・注文訂正
    IPO_PO = 6  # IPO・PO
    OFF_HOURS_TRADING = 7  # 立会外
    FRACTIONAL_STOCK = 8  # 単元未満株
    THEME_INVESTMENT = 9  # テーマ投資

class BASIC_SEARCH_CATEGORY(Enum):
    MARKET = 0
    SIZE = 1
    INDICATOR = 2
    SECTOR = 3
    NISA = 4
    LEVERAGE = 5
    SCORE = 6
    TRADE_VOLUME = 7
    ALL = 8

class MARKET_OPTIONS(Enum):
    JP_TSE_Prime = 0
    JP_TSE_Standard = 1
    JP_TSE_Growth = 2
    JP_TSE_ETF = 3
    JP_TSE_REIT = 4
    JP_Regional_Markets = 5
    JP_Others = 6

class SIZE_OPTIONS(Enum):
    LARGE = 0
    MID = 1
    SMALL = 2

class INDICATOR_OPTIONS(Enum):
    NIKKEI_225 = 0
    TOPIX = 1
    JPX400 = 2

class LEVERAGE_OPTIONS(Enum):
    LEVERAGE = 0
    INVERSE = 1

class ADVANCED_SEARCH_CATEGORY(Enum):
    FINANCIAL = 0
    CONSENSUS = 1
    PERFORMANCE = 2
    TECHNICAL = 3
    OTHERS = 4

class SEARCH_METHOD(Enum):
    RANGE = 0
    DROPDOWN = 1
    RANGE_DROPDOWN = 2
    TWO_DROPDOWN = 3
    SLIDER = 4
    DROPDOWN_SLIDER = 5
    BOOLEAN = 6
    TABLE = 7

class ADVANCED_SEARCH_OPTION(NamedTuple):
    option_type: ADVANCED_SEARCH_CATEGORY
    search_method: SEARCH_METHOD
    index: int
    title: str
    variables: dict[int, str] | None = None

#  dropdown options
PER_CHANGE_RATE_TERMS = {0: '5営業日前', 1: '20営業日前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '1年前', 5: '3年前', 6: '5年前'}
PBR_CHANGE_RATE_TERMS = {0: '5営業日前', 1: '20営業日前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '1年前', 5: '3年前', 6: '5年前'}
REVENUE_CHANGE_RATE_TERMS = {0: '前年度比', 1: '3年前年度比', 2: '5年前年度比', 3: '前年同四半期比'}
ORDINARY_PROFIT_CHANGE_RATE_TERMS = {0: '前年度比', 1: '3年前年度比', 2: '5年前年度比', 3: '前年同四半期比'}
DIVIDEND_YIELD_CHANGE_RATE_TERMS = {0: '5営業日前', 1: '20営業日前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '1年前', 5: '3年前', 6: '5年前'}
CONSENSUS_PREDICTION_CHANGE_RATE_TERMS = {0: '5営業日前', 1: '20営業日前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '12ヶ月前'}
TARGET_PRICE_DEVIATION_RATE_CHANGE_RATE_TERMS = {0: '1週間前', 1: '1ヶ月前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '12ヶ月前'}
COMPANY_PERFORMANCE_FORECAST_TERMS = {0: '1週間前', 1: '1ヶ月前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '12ヶ月前'}
RATING_MODIFY_TERMS = {0: '1週間前', 1: '1ヶ月前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '12ヶ月前'}
CONSENSUS_RATING_CHANGE_TERMS = {0: '1週間前', 1: '1ヶ月前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '12ヶ月前'}
COMPANY_PERFORMANCE_FORECAST_MODIFY_TERMS = {0: '1週間前', 1: '1ヶ月前', 2: '3ヶ月前', 3: '6ヶ月前', 4: '12ヶ月前'}
NEW_PRICE_FOR_A_YEAR_TERMS = {0: '今日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前'}
PRICE_CHANGE_RATE_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前', 6: '3年前', 7: '5年前'}
VOLUME_CHANGE_RATE_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前'}
COMPARE_WITH_NIKKEI225_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前', 6: '3年前', 7: '5年前'}
TECHNICAL_CROSS_TERMS = {0: '5 日/25日', 1: '25日/75日', 2: '75日/200日', 3: '13週/26週', 4: '26週/52週', 5: '9ヶ月/24ヶ月', 6: '24ヶ月/60ヶ月'}
TECHNICAL_SIGNALS = {0: '買いシグナル', 1: '売りシグナル'}
STOCHASTIC_SIGNALS = {0: '買いシグナル', 1: '売りシグナル'}
SLOW_STOCHASTIC_SIGNALS = {0: '買いシグナル', 1: '売りシグナル'}
CRASH_RATE_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前', 6: '3年前', 7: '5年前'}
MEAN_TRADING_VOLUME_TERMS = {0: '5日', 1: '20日'}
PRICE_MA_DEVIATION_RATE_TERMS = {0: '5営業日前', 1: '25営業日前', 2: '75営業日前', 3: '200営業日前', 4: '13週', 5: '26週', 6: '52週', 7: '9ヶ月', 8: '24ヶ月', 9: '60ヶ月'}
MA_DEVIATION_RATE_TERMS = {0: '5営業日前', 1: '25営業日前', 2: '75営業日前', 3: '200営業日前', 4: '13週', 5: '26週', 6: '52週', 7: '9ヶ月', 8: '24ヶ月', 9: '60ヶ月'}
PRICE_MA_DEVIATION_RATE_TERMS = {0: '今日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前'}
CHANGE_RATE_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前', 6: '3年前', 7: '5年前'}
VOLUME_RATE_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前'}
SALES_RATE_TERMS = {0: '前日', 1: '5営業日前', 2: '20営業日前', 3: '3ヶ月前', 4: '6ヶ月前', 5: '1年前'}
RSI_TERMS = {0: '過去14日', 1: '過去9 週', 2: '過去9 ヶ月'}

# two dropdown options
DMI_MACD_TERMS = {0: '日足', 1: '週足'}
DMI_MACD_SIGNALS = {0: '買いシグナル', 1: '売りシグナル'}

PER = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 0, "PER(株価収益率)")
PBR = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 1, "PBR(株価純資産倍率)")
DIVIDEND_YIELD = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 2, "配当利回り")
BPS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 3, "BPS(1株当たり純資産)")
EPS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 4, "EPS(1株当たり当期利益)")
ROE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 5, "ROE(自己資本利益率)")
ROA = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 6, "ROA(総資産当期利益率)(%)")
PER_CHANGE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE_DROPDOWN, 7, "PER変化率(%)", PER_CHANGE_RATE_TERMS)
# next line
PBR_CHANGE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE_DROPDOWN, 8, "PBR変化率(%)", PBR_CHANGE_RATE_TERMS)
NET_YIELD = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 9, "益利回り(%)")
REVENUE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 10, "売上高(百万円)")
ORDINARY_PROFIT = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 11, "経常利益(百万円)")
NET_PROFIT = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 12, "当期純利益(百万円)")
EQUITY_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 13, "自己資本比率(%)")
# 有利子負債自己資本比率
DEBT_EQUITY_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 14, "有利子負債自己資本比率(%)")
# 流動比率
CURRENT_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 15, "流動比率(%)")
# '当座比率',
QUICK_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 16, "当座比率(%)")
# 'PSR\n(株価売上高倍率)',
PSR = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 17, "PSR(株価売上高倍率)(倍)")
# 'PCFR\n(株価キャッシュフロー倍率)',
PCFR = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 18, "PCFR(株価キャッシュフロー倍率)(倍)")
# '売上高変化率',
REVENUE_CHANGE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE_DROPDOWN, 19, "売上高変化率(%)", REVENUE_CHANGE_RATE_TERMS)
# '経常利益変化率',
ORDINARY_PROFIT_CHANGE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE_DROPDOWN, 20, "経常利益変化率(%)", ORDINARY_PROFIT_CHANGE_RATE_TERMS)
# '売上高営業利益率',
OPERATING_MARGIN = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 21, "売上高営業利益率(%)")
# '売上高経常利益率',
ORDINARY_PROFIT_MARGIN = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 22, "売上高経常利益率(%)")
# '配当利回り変化率'
DIVIDEND_YIELD_CHANGE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE_DROPDOWN, 23, "配当利回り変化率(%)", DIVIDEND_YIELD_CHANGE_RATE_TERMS)
# '海外売上高比率'
OVERSEAS_REVENUE_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 24, "海外売上高比率(%)")
# '売上債権回転率'
ACCOUNTS_RECEIVABLE_TURNOVER = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 25, "売上債権回転率(回)")
# 'EV/EBITDA倍率',
EV_EBITDA_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 26, "EV/EBITDA倍率(倍)")
# '棚卸資産回転率',
INVENTORY_TURNOVER = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 27, "棚卸資産回転率(回)")
# 'インタレストカバレッジレシオ'
INTEREST_COVERAGE_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.FINANCIAL, SEARCH_METHOD.RANGE, 28, "インタレストカバレッジレシオ(倍)")
ADVANCED_FINANCIAL_OPTIONS_COUNT = 29

# 'PER\n(株価収益率)(予)'
PER_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE_DROPDOWN, 0, "PER(株価収益率)(予)(倍)", CONSENSUS_PREDICTION_CHANGE_RATE_TERMS)
# '配当利回り(予)'
DIVIDEND_YIELD_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 1, "配当利回り(予)(%)")
# 'BPS\n(1株当たり純資産)(予)'
BPS_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 2, "BPS(予)(円)")
# 'EPS\n(1株当たり当期利益)(予)'
EPS_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 3, "EPS(1株当たり当期利益)(予)(円)")
# 'PEG(予)'
PEG_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 4, "PEG(予)(倍)")
# 'PER変化率(予)'
PER_CHANGE_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 5, "PER変化率(予)(%)")
# '売上高(予)'
REVENUE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 6, "売上高(予)(百万円)")
# '経常利益(予)'
ORDINARY_PROFIT_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 7, "経常利益(予)(百万円)")
# '売上高当期純利益率(予)'
NET_PROFIT_MARGIN_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 8, "売上高当期純利益率(予)(%)")
# '長期成長率(予)'
LONG_TERM_GROWTH_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 9, "長期成長率(予)(%)")
# '売上高成長率(予)'
SALES_GROWTH_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 10, "売上高成長率(予)(%)")
# '経常利益成長率(予)'
ORDINARY_PROFIT_GROWTH_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 11, "経常利益成長率(予)(%)")
# '売上高変化率(予)'
REVENUE_CHANGE_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE_DROPDOWN, 12, "売上高変化率(予)(%)", CONSENSUS_PREDICTION_CHANGE_RATE_TERMS)
# '経常利益変化率(予)'
ORDINARY_PROFIT_CHANGE_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE_DROPDOWN, 13, "経常利益変化率(予)(%)", CONSENSUS_PREDICTION_CHANGE_RATE_TERMS)
# '配当利回り変化率(予)'
DIVIDEND_YIELD_CHANGE_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE_DROPDOWN, 14, "配当利回り変化率(予)(%)", CONSENSUS_PREDICTION_CHANGE_RATE_TERMS)
# '過去5年平均営業利益\n成長率(予)'
FIVE_YEAR_AVG_OPERATING_PROFIT_GROWTH_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 15, "過去5年平均営業利益成長率(予)(%)")
# '過去3年平均売上高\n成長率(予)'
THREE_YEAR_AVG_SALES_GROWTH_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 16, "過去3年平均売上高成長率(予)(%)")
# '業績予想修正率(予)'
PERFORMANCE_FORECAST_REVISION_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 17, "業績予想修正率(予)(%)")
# '有利子負債/当期利益(予)'
DEBT_TO_NET_PROFIT_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 18, "有利子負債当期利益率(予)(%)")
# '目標株価乖離率(予)'
TARGET_PRICE_DEVIATION_RATE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 19, "目標株価乖離率(予)(%)")
# '目標株価乖離率の変化率(予)'
TARGET_PRICE_DEVIATION_RATE_CHANGE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE_DROPDOWN, 20, "目標株価乖離率の変化率(予)(%)", TARGET_PRICE_DEVIATION_RATE_CHANGE_RATE_TERMS)
# 'コンセンサスレーティング(予)'
CONSENSUS_RATING_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 21, "コンセンサスレーティング(予)")
# 'レーティング上方修正'
RATING_UPGRADE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.DROPDOWN, 22, "レーティング上方修正", RATING_MODIFY_TERMS)
# 'レーティング下方修正'
RATING_DOWNGRADE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.DROPDOWN, 23, "レーティング下方修正", RATING_MODIFY_TERMS)
# 'コンセンサスレーティング変化幅(予)'
CONSENSUS_RATING_CHANGE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE_DROPDOWN, 24, "コンセンサスレーティング変化幅(予)")
# '予想ブローカー数'
NUMBER_OF_BROKERS_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.RANGE, 25, "予想ブローカー数")
# '会社業績予想上方修正'
COMPANY_PERFORMANCE_FORECAST_UP_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.DROPDOWN, 26, "会社予想上方修正", COMPANY_PERFORMANCE_FORECAST_MODIFY_TERMS)
# '会社業績予想下方修正'
COMPANY_PERFORMANCE_FORECAST_DOWN_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.DROPDOWN, 27, "会社予想下方修正", COMPANY_PERFORMANCE_FORECAST_MODIFY_TERMS)
# 'サプライズ(決算)'
EARNINGS_SURPRISE_CONSENSUS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.CONSENSUS, SEARCH_METHOD.DROPDOWN_SLIDER, 28, "サプライズ(決算)")
ADVANCED_CONSENSUS_OPTIONS_COUNT = 29

PRICE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 0, "株価(円)")
CRASH = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 1, "株価騰落【円】(円)", CRASH_RATE_TERMS)
CRASH_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 2, "株価騰落【率】(%)", CRASH_RATE_TERMS)
CAPITALIZATION = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 3, "時価総額(百万円)")
DAILY_TRADING_VOLUME = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 4, "日中売買代金(千円)")
MEAN_TRADING_VOLUME = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 5, "平均売買代金(千円)", MEAN_TRADING_VOLUME_TERMS)
PRICE_MA_DEVIATION_RATE_1 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 6, "株価移動平均線乖離率①(%)", PRICE_MA_DEVIATION_RATE_TERMS)
PRICE_MA_DEVIATION_RATE_2 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 7, "株価移動平均線乖離率②(%)", PRICE_MA_DEVIATION_RATE_TERMS)
PRICE_MA_DEVIATION_RATE_3 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 8, "株価移動平均線乖離率③(%)", PRICE_MA_DEVIATION_RATE_TERMS)
# next line
NEW_LOW_FOR_A_YEAR = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.DROPDOWN, 9, "年初来安値更新", NEW_PRICE_FOR_A_YEAR_TERMS)
NEW_HIGH_FOR_A_YEAR = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.DROPDOWN, 10, "年初来高値更新", NEW_PRICE_FOR_A_YEAR_TERMS)
PCT_INCREASE_FROM_LOW = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 11, "年初来安値からの上昇率(%)")
PCT_DECREASE_FROM_HIGH = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 12, "年初来高値からの下落率(%)")
INCREASE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 13, "値上がり率(%)", PRICE_CHANGE_RATE_TERMS)
DECREASE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 14, "値下がり率(%)", PRICE_CHANGE_RATE_TERMS)
PCT_INCREASE_FROM_52W_LOW = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 15, "過去52週安値からの上昇率(%)")
PCT_DECREASE_FROM_52W_HIGH = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 16, "過去52週高値からの下落率(%)")
# next line
VOLUME_MEAN_RATE_6D_PER_25 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 17, "出来高平均6日/25日倍率(倍)")
VOLUME_INCREASE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 18, "出来高増加率(倍)", VOLUME_CHANGE_RATE_TERMS)
SALES_VOLUME_INCREASE_RATE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE_DROPDOWN, 19, "売買代金増加率(倍)", SALES_RATE_TERMS)
VOLATILITY_60D = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 20, "過去60日ボラティリティ(%)")
OUTPERFORMANCE_NIKKEI225 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.DROPDOWN, 21, "日経平均の値上がり率上回り", COMPARE_WITH_NIKKEI225_TERMS)
UNDERPERFORMANCE_NIKKEI225 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.DROPDOWN, 22, "日経平均の値下がり率下回り", COMPARE_WITH_NIKKEI225_TERMS)
CREDIT_BALANCE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 23, "信用残/売買高レシオ(倍)")
CREDIT_BALANCE_LONG = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 24, "信用残(買)(株)")
CREDIT_BALANCE_SHORT = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 25, "信用残(売)(株)")
# next line
CREDIT_BALANCE_RATE_LONG_1W = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 26, "信用残前週比(買)(株)")
CREDIT_BALANCE_RATE_SHORT_1W = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 27, "信用残前週比(売)(株)")
CREDIT_RATIO = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.PERFORMANCE, SEARCH_METHOD.RANGE, 28, "信用倍率(倍)")
ADVANCED_PERFORMANCE_OPTIONS_COUNT = 29

# 'ゴールデンクロス①'
GOLDEN_CROSS_1 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 0, "ゴールデンクロス①", TECHNICAL_CROSS_TERMS)
# 'ゴールデンクロス②',
GOLDEN_CROSS_2 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 1, "ゴールデンクロス②", TECHNICAL_CROSS_TERMS)
# 'ゴールデンクロス③'
GOLDEN_CROSS_3 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 2, "ゴールデンクロス③", TECHNICAL_CROSS_TERMS)
# 'デッドクロス①'
DEAD_CROSS_1 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 3, "デッドクロス①", TECHNICAL_CROSS_TERMS)
# 'デッドクロス②'
DEAD_CROSS_2 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 4, "デッドクロス②", TECHNICAL_CROSS_TERMS)
# 'デッドクロス③'
DEAD_CROSS_3 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 5, "デッドクロス③", TECHNICAL_CROSS_TERMS)
# '一目均衡雲抜け上'
ICHIMOKU_CLOUD_BREAKOUT_UP = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.BOOLEAN, 6, "一目均衡雲抜け上")
# '一目均衡雲抜け下'
ICHIMOKU_CLOUD_BREAKOUT_DOWN = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.BOOLEAN, 7, "一目均衡雲抜け下")
# '新値3本足'
NEW_PRICE_3LINE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 8, "新値3本足", TECHNICAL_SIGNALS)
# 'ボリンジャーバンド'
BOLLINGER_BANDS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.TWO_DROPDOWN, 9, "ボリンジャーバンド")
# 'RSI'
RSI = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE_DROPDOWN, 10, "RSI(%)", RSI_TERMS)
# 'RCI'
RCI = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 11, "RCI", TECHNICAL_SIGNALS)
# 'ストキャスティクス'
STOCHASTIC = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 12, "ストキャスティクス", TECHNICAL_SIGNALS)
# 'スローストキャスティクス'
SLOW_STOCHASTIC = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.DROPDOWN, 13, "スローストキャスティクス", TECHNICAL_SIGNALS)
# 'DMI'
DMI = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.TWO_DROPDOWN, 14, "DMI", {0: DMI_MACD_TERMS, 1: DMI_MACD_SIGNALS})
# 'サイコロジカルライン'
PSYCHOLOGICAL_LINE = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 15, "サイコロジカルライン(%)")
# 'MACD'
MACD = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.TWO_DROPDOWN, 16, "MACD", {0: DMI_MACD_TERMS, 1: DMI_MACD_SIGNALS})
# 'ベータ(対日経平均)'
BETA_NIKKEI225 = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 17, "ベータ(対日経平均)")
# 'ベータ(対TOPIX)'
BETA_TOPIX = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 18, "ベータ(対TOPIX)")
# 'ベータ(対東証業種指数)'
BETA_TSE_SECTOR = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 19, "ベータ(対東証業種指数)")
# '金・米ドルスポット感応度'
GOLD_USD_SPOT_SENSITIVITY = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 20, "金・米ドルスポット感応度")
# 'VIX恐怖指数感応度'
VIX_FEAR_INDEX_SENSITIVITY = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 21, "VIX恐怖指数感応度")
# 'CRB商品指数感応度'
CRB_COMMODITY_INDEX_SENSITIVITY = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 22, "CRB商品指数感応度")
# 'ドル建日経225感応度'
DOLLAR_BASED_NIKKEI225_SENSITIVITY = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 23, "ドル建日経225感応度")
# 'WTI原油先物感応度'
WTI_CRUDE_OIL_FUTURES_SENSITIVITY = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 24, "WTI原油先物感応度")
# '日本円感応度'
JAPANESE_YEN_SENSITIVITY = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.TECHNICAL, SEARCH_METHOD.RANGE, 25, "日本円感応度")
ADVANCED_TECHNICAL_OPTIONS_COUNT = 26

# 決算月
SETTLEMENT_MONTH = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.OTHERS, SEARCH_METHOD.TABLE, 0, "決算月")
# 優待権利確定月
BENEFIT_RIGHTS_CONFIRMATION_MONTH = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.OTHERS, SEARCH_METHOD.TABLE, 1, "優待権利確定月")
# 売建可能銘柄
SHORT_SELLING_POSSIBLE_STOCKS = ADVANCED_SEARCH_OPTION(ADVANCED_SEARCH_CATEGORY.OTHERS, SEARCH_METHOD.BOOLEAN, 2, "売建可能銘柄")
ADVANCED_OTHERS_OPTIONS_COUNT = 3